set_property IOSTANDARD LVCMOS33 [get_ports {OUT_LED_DATA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_LED_DATA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_LED_DATA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OUT_LED_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports PL_KEY2]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports PL_KEY1]
set_property IOSTANDARD LVCMOS33 [get_ports SCL]
set_property IOSTANDARD LVCMOS33 [get_ports SDA]
set_property PACKAGE_PIN G15 [get_ports {OUT_LED_DATA[3]}]
set_property PACKAGE_PIN G14 [get_ports {OUT_LED_DATA[1]}]
set_property PACKAGE_PIN M17 [get_ports {OUT_LED_DATA[2]}]
set_property PACKAGE_PIN M15 [get_ports {OUT_LED_DATA[0]}]
set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN M19 [get_ports PL_KEY1]
set_property PACKAGE_PIN M20 [get_ports PL_KEY2]
set_property PACKAGE_PIN E17 [get_ports rst_n]
set_property PACKAGE_PIN G17 [get_ports SCL]
set_property PACKAGE_PIN G18 [get_ports SDA]

create_clock -period 20.000 -name clk -waveform {0.000 10.000} [get_ports clk]
